name: Create a release for num-tabs package

on:
  workflow_dispatch:
  push:
      branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Package extension for release
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        yarn install
        yarn build
        zip -r num-tabs.zip num-tabs/
    - name: Publish release
      uses: marvinpinto/action-automatic-releases@latest
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          num-tabs.zip

